#!/usr/bin/env bash
# The script installs and configures Nginx to serve
# 'Hello World!' at the root URL on port 80.

apt-get -y update
apt-get -install nginx
ufw allow "NGINX HTTP"
echo 'Hello World!' > /var/www/html/index.html
service nginx restart
