#!/usr/bin/env bash
# install and configure nginx on web-01
# should return 'Hello World!' upon a GET request at the root

apt-get -y update
apt-get -insall nginx
ufw allow "NGINX HTTP"
echo 'Hello World!' > /var/www/html/index.html
service nginx restart
