#!/usr/bin/env bash
# The script installs and configures Nginx to serve
# 'Hello World!' at the root URL on port 80.

sudo apt-get -y update
sudo apt-get -install nginx
sudo ufw allow "NGINX HTTP"
echo 'Hello World!' > /var/www/html/index.html

sudo nginx -t
sudo service nginx restart
