#!/usr/bin/env bash
# Run the Docker container with port 8080 mapped to port 80
# Verify the Apache container is running
# Test if the page is correctly served
docker run -p 8080:80 -d apache-hello
docker ps
curl 0:8080
sudo apt-get update -y
sudo apt-get install -y apache2
echo "Hello ALX" | sudo tee -a /var/www/html/index.html
sudo service apache2 start
sudo service apache2 status
